//src\constants\godsAskingToolset.js
const runeIsopsephia = {
  ᚠ: { value: 2, latin: "F" },
  ᚢ: { value: 3, latin: "U" },
  ᚦ: { value: 4, latin: "TH" },
  ᚨ: { value: 5, latin: "A" },
  ᚱ: { value: 6, latin: "R" },
  ᚲ: { value: 7, latin: "K" },
  ᚷ: { value: 8, latin: "G" },
  ᚹ: { value: 9, latin: "W" },
  ᚺ: { value: 10, latin: "H" },
  ᚾ: { value: 11, latin: "N" },
  ᛁ: { value: 12, latin: "I" },
  ᛃ: { value: 13, latin: "J" },
  ᛇ: { value: 14, latin: "EI" },
  ᛈ: { value: 15, latin: "P" },
  ᛉ: { value: 16, latin: "Z" },
  ᛋ: { value: 17, latin: "S" },
  ᛏ: { value: 18, latin: "T" },
  ᛒ: { value: 19, latin: "B" },
  ᛖ: { value: 20, latin: "E" },
  ᛗ: { value: 21, latin: "M" },
  ᛚ: { value: 22, latin: "L" },
  ᛜ: { value: 23, latin: "NG" },
  ᛞ: { value: 24, latin: "D" },
  ᛟ: { value: 25, latin: "O" },
};

const latinToRune = Object.fromEntries(
  Object.entries(runeIsopsephia).map(([rune, data]) => [
    data.latin.toLowerCase(),
    rune,
  ])
);

const teqValues = {
  A: 5,
  B: 20,
  C: 2,
  D: 23,
  E: 13,
  F: 12,
  G: 11,
  H: 3,
  I: 0,
  J: 7,
  K: 17,
  L: 1,
  M: 21,
  N: 24,
  O: 10,
  P: 4,
  Q: 16,
  R: 14,
  S: 15,
  T: 9,
  U: 25,
  V: 22,
  W: 8,
  X: 6,
  Y: 18,
  Z: 19,
};

const trigrams = [
  { value: 0, base3: "000", trigram: "000", letter: "I" },
  { value: 1, base3: "001", trigram: "00+", letter: "N" },
  { value: 2, base3: "002", trigram: "00-", letter: "C" },
  { value: 3, base3: "010", trigram: "0+0", letter: "H" },
  { value: 4, base3: "011", trigram: "0++", letter: "P" },
  { value: 5, base3: "012", trigram: "0+-", letter: "A" },
  { value: 6, base3: "020", trigram: "0-0", letter: "X" },
  { value: 7, base3: "021", trigram: "0-+", letter: "J" },
  { value: 8, base3: "022", trigram: "0--", letter: "W" },
  { value: 9, base3: "100", trigram: "+00", letter: "T" },
  { value: 10, base3: "101", trigram: "+0+", letter: "O" },
  { value: 11, base3: "102", trigram: "+0-", letter: "G" },
  { value: 12, base3: "110", trigram: "++0", letter: "F" },
  { value: 13, base3: "111", trigram: "+++", letter: "E" },
  { value: 14, base3: "112", trigram: "++-", letter: "R" },
  { value: 15, base3: "120", trigram: "+-0", letter: "S" },
  { value: 16, base3: "121", trigram: "+-+", letter: "Q" },
  { value: 17, base3: "122", trigram: "+--", letter: "K" },
  { value: 18, base3: "200", trigram: "-00", letter: "Y" },
  { value: 19, base3: "201", trigram: "-0+", letter: "Z" },
  { value: 20, base3: "202", trigram: "-0-", letter: "B" },
  { value: 21, base3: "210", trigram: "-+0", letter: "M" },
  { value: 22, base3: "211", trigram: "-++", letter: "V" },
  { value: 23, base3: "212", trigram: "-+-", letter: "D" },
  { value: 24, base3: "220", trigram: "--0", letter: "N" },
  { value: 25, base3: "221", trigram: "--+", letter: "U" },
  { value: 26, base3: "222", trigram: "---", letter: "Vulva" },
];

const GodsAskingToolset = [
  // Хоггвы (id: 0–35, 36 символов)
  { symbol: "⅄", isRune: false, id: 0, indexInJar: 0 },
  { symbol: "ͱ", isRune: false, id: 1, indexInJar: 1 },
  { symbol: "ɾ", isRune: false, id: 2, indexInJar: 2 },
  { symbol: "q", isRune: false, id: 3, indexInJar: 3 },
  { symbol: "ʌ", isRune: false, id: 4, indexInJar: 4 },
  { symbol: "p", isRune: false, id: 5, indexInJar: 5 },
  { symbol: "չ", isRune: false, id: 6, indexInJar: 6 },
  { symbol: "↷", isRune: false, id: 7, indexInJar: 7 },
  { symbol: "m", isRune: false, id: 8, indexInJar: 8 },
  { symbol: "ϙ", isRune: false, id: 9, indexInJar: 9 },
  { symbol: "I", isRune: false, id: 10, indexInJar: 10 },
  { symbol: "C", isRune: false, id: 11, indexInJar: 11 },
  { symbol: "ʙ", isRune: false, id: 12, indexInJar: 12 },
  { symbol: "ʜ", isRune: false, id: 13, indexInJar: 13 },
  { symbol: "O", isRune: false, id: 14, indexInJar: 14 },
  { symbol: "Ƒ", isRune: false, id: 15, indexInJar: 15 },
  { symbol: "ɯ", isRune: false, id: 16, indexInJar: 16 },
  { symbol: "ϵ", isRune: false, id: 17, indexInJar: 17 },
  { symbol: "ʞ", isRune: false, id: 18, indexInJar: 18 },
  { symbol: "d", isRune: false, id: 19, indexInJar: 19 },
  { symbol: "ψ", isRune: false, id: 20, indexInJar: 20 },
  { symbol: "Ξ", isRune: false, id: 21, indexInJar: 21 },
  { symbol: "ʀ", isRune: false, id: 22, indexInJar: 22 },
  { symbol: "Պ", isRune: false, id: 23, indexInJar: 23 },
  { symbol: "b", isRune: false, id: 24, indexInJar: 24 },
  { symbol: "Ʋ", isRune: false, id: 25, indexInJar: 25 },
  { symbol: "⊥", isRune: false, id: 26, indexInJar: 26 },
  { symbol: "է", isRune: false, id: 27, indexInJar: 27 },
  { symbol: "T", isRune: false, id: 28, indexInJar: 28 },
  { symbol: "Ɣ", isRune: false, id: 29, indexInJar: 29 },
  { symbol: "Δ", isRune: false, id: 30, indexInJar: 30 },
  { symbol: "փ", isRune: false, id: 31, indexInJar: 31 },
  { symbol: "n", isRune: false, id: 32, indexInJar: 32 },
  { symbol: "ᛋ", isRune: false, id: 33, indexInJar: 33 },
  { symbol: "⁝", isRune: false, id: 34, indexInJar: 34 },
  { symbol: "‡", isRune: false, id: 35, indexInJar: 35 },
  // Руны (id: 36–60, 25 символов)
  { symbol: "ᚠ", isRune: true, id: 36, indexInJar: 36 },
  { symbol: "ᚢ", isRune: true, id: 37, indexInJar: 37 },
  { symbol: "ᚦ", isRune: true, id: 38, indexInJar: 38 },
  { symbol: "ᚨ", isRune: true, id: 39, indexInJar: 39 },
  { symbol: "ᚱ", isRune: true, id: 40, indexInJar: 40 },
  { symbol: "ᚲ", isRune: true, id: 41, indexInJar: 41 },
  { symbol: "ᚷ", isRune: true, id: 42, indexInJar: 42 },
  { symbol: "ᚹ", isRune: true, id: 43, indexInJar: 43 },
  { symbol: "ᚺ", isRune: true, id: 44, indexInJar: 44 },
  { symbol: "ᚾ", isRune: true, id: 45, indexInJar: 45 },
  { symbol: "ᛁ", isRune: true, id: 46, indexInJar: 46 },
  { symbol: "ᛃ", isRune: true, id: 47, indexInJar: 47 },
  { symbol: "ᛇ", isRune: true, id: 48, indexInJar: 48 },
  { symbol: "ᛈ", isRune: true, id: 49, indexInJar: 49 },
  { symbol: "ᛉ", isRune: true, id: 50, indexInJar: 50 },
  { symbol: "ϟ", isRune: true, id: 51, indexInJar: 51 },
  { symbol: "ᛏ", isRune: true, id: 52, indexInJar: 52 },
  { symbol: "ᛒ", isRune: true, id: 53, indexInJar: 53 },
  { symbol: "ᛖ", isRune: true, id: 54, indexInJar: 54 },
  { symbol: "ᛗ", isRune: true, id: 55, indexInJar: 55 },
  { symbol: "ᛚ", isRune: true, id: 56, indexInJar: 56 },
  { symbol: "ᛜ", isRune: true, id: 57, indexInJar: 57 },
  { symbol: "ᛟ", isRune: true, id: 58, indexInJar: 58 },
  { symbol: "ᛞ", isRune: true, id: 59, indexInJar: 59 },
  { symbol: "⮽", isRune: true, id: 60, indexInJar: 60 },
];

export { runeIsopsephia, latinToRune, teqValues, trigrams, GodsAskingToolset };
